wandb_version: 1

timesteps:
  desc: null
  value: 6
prediction:
  desc: null
  value: vxt
dataset:
  desc: null
  value: mnist
degradation:
  desc: null
  value: black_blur
batch_size:
  desc: null
  value: 64
dim:
  desc: null
  value: 64
lr:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 3
noise_schedule:
  desc: null
  value: cosine
loss_weighting:
  desc: null
  value: false
var_sampling_step:
  desc: null
  value: 1
min_t2_step:
  desc: null
  value: 1
baseline:
  desc: null
  value: xxxx
multiscale_vae:
  desc: null
  value: false
autoencoder:
  desc: null
  value: false
kl_annealing:
  desc: null
  value: 5000
cold_perturb:
  desc: null
  value: false
vae:
  desc: null
  value: false
vae_beta:
  desc: null
  value: 0.1
latent_dim:
  desc: null
  value: 32
ris_noise:
  desc: null
  value: false
add_noise:
  desc: null
  value: false
break_symmetry:
  desc: null
  value: false
noise_scale:
  desc: null
  value: 0.01
vae_loc:
  desc: null
  value: emb
vae_inject:
  desc: null
  value: concat
xt_dropout:
  desc: null
  value: 0
load_checkpoint:
  desc: null
  value: false
sample_interval:
  desc: null
  value: 1
n_samples:
  desc: null
  value: 60
fix_sample:
  desc: null
  value: true
skip_ema:
  desc: null
  value: false
model_ema_decay:
  desc: null
  value: 0.998
cluster:
  desc: null
  value: false
skip_wandb:
  desc: null
  value: false
verbose:
  desc: null
  value: false
multi_gpu:
  desc: null
  value: false
fid_only:
  desc: null
  value: false
test_run:
  desc: null
  value: false
num_downsamples:
  desc: null
  value: 2
device:
  desc: null
  value: mps
image_size:
  desc: null
  value: 28
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721748237.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.16.5
      8:
      - 1
      - 5
      13: darwin-arm64
